/* In-page test harness for Dead Embers (dev only, never bundled). Load in a running page: fetch("tools/harness.js").then(r=>r.text()).then(eval)
   Deterministic frames (20/s via sim), BFS walking (goto), fight/search bots and state(). */
window.__T = 1e6;
window.sim = (sec, ctl) => { const n = Math.round(sec * 20); for (let i = 0; i < n; i++) { if (ctl && ctl(i) === 'stop') return i / 20; __T += 50; frame(__T); } return sec; };
window.kd = c => dispatchEvent(new KeyboardEvent('keydown', { code: c })); window.ku = c => dispatchEvent(new KeyboardEvent('keyup', { code: c }));
window.skipDlg = () => { if (UI.blocking()) { kd('Space'); ku('Space'); } };
window.go = (pts, near, maxS) => { let i = 0; const t = sim(maxS || 40, () => { const [tx, ty] = pts[i], p = G.p, dx = tx - p.x, dy = ty - p.y, d = Math.hypot(dx, dy); skipDlg(); if (d < (i === pts.length - 1 ? near : 0.5)) { i++; if (i >= pts.length) { INPUT.mx = INPUT.my = 0; return 'stop'; } return; } INPUT.mx = dx / d; INPUT.my = dy / d; }); INPUT.mx = INPUT.my = 0; return t; };
window.path = (tx, ty) => { const sx = Math.floor(G.p.x), sy = Math.floor(G.p.y), gx = Math.floor(tx), gy = Math.floor(ty); const prev = new Int32Array(W * H).fill(-1), q = [sy * W + sx]; prev[q[0]] = q[0]; for (let h = 0; h < q.length; h++) { const i = q[h], x = i % W, y = (i - x) / W; if (x === gx && y === gy) break; for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const nx = x + dx, ny = y + dy, j = ny * W + nx; if (nx < 0 || ny < 0 || nx >= W || ny >= H || prev[j] >= 0 || SOLID.has(tileAt(nx, ny))) continue; prev[j] = i; q.push(j); } } let i = gy * W + gx; if (prev[i] < 0) return null; const pts = []; while (i !== prev[i]) { const x = i % W; pts.unshift([x + 0.5, (i - x) / W + 0.5]); i = prev[i]; } return pts; };
window.goto = (tx, ty, near, maxS) => { const pts = path(tx, ty); if (!pts) return 'nopath'; pts.push([tx, ty]); return go(pts, near || 0.5, maxS || 60); };
window.clearFoes = () => { for (const e of Combat.enemies.slice()) Combat.despawn && Combat.despawn(e); };
window.fightBot = (ids, gun, maxS) => { if (ids) { clearFoes(); window.__won = 0; window.__lost = 0; fight(ids, { onWin: () => { __won = 1; return 'Won.'; }, onFlee: () => { __lost = 'flee'; return ''; } }); } const cv = document.querySelector('#view canvas'); let swings = 0, minHp = G.p.hp;
  const t = sim(maxS || 40, i => { if (ids && (__won || __lost)) return 'stop'; minHp = Math.min(minHp, G.p.hp); if (UI.blocking()) { skipDlg(); return; } const p = G.p; let b = null, bd = 99; for (const e of Combat.enemies) { if (e.dead) continue; const d = Math.hypot(e.x - p.x, e.y - p.y); if (d < bd) { bd = d; b = e; } } if (!b) return ids ? undefined : 'stop'; const s = R.tileToScreen(b.x, b.y, 1); INPUT.aimX = s.x; INPUT.aimY = s.y;
    const want = gun ? 4.5 : 1.0; if (bd > want + 0.3) { INPUT.mx = (b.x - p.x) / bd; INPUT.my = (b.y - p.y) / bd; } else { INPUT.mx = INPUT.my = 0; }
    if (i % 4 === 0 && bd < (gun ? 7 : 1.7)) { swings++; if (gun) { cv.dispatchEvent(new PointerEvent('pointerdown', { clientX: s.x, clientY: s.y, button: 0, pointerType: 'mouse', bubbles: true })); dispatchEvent(new PointerEvent('pointerup', { clientX: s.x, clientY: s.y, button: 0, pointerType: 'mouse', bubbles: true })); dispatchEvent(new MouseEvent('mouseup')); } else { kd('KeyJ'); ku('KeyJ'); } }
    if (Combat.grabbed && i % 2) { kd('KeyJ'); ku('KeyJ'); } });
  INPUT.mx = INPUT.my = 0; return { won: window.__won, secs: t, swings, minHp: Math.round(minHp), hp: Math.round(G.p.hp), kills: G.stats.kills }; };
window.nearestCont = () => WORLD.containers.filter(c => containerState(c) !== 'empty').sort((a, b) => ((a.x - G.p.x) ** 2 + (a.y - G.p.y) ** 2) - ((b.x - G.p.x) ** 2 + (b.y - G.p.y) ** 2))[0];
window.searchNearest = () => { const c = nearestCont(); const adj = [[0, 1], [1, 0], [-1, 0], [0, -1]].map(([dx, dy]) => [c.x + dx + 0.5, c.y + dy + 0.5]).find(([x, y]) => !solidAt(x, y)); goto(adj[0], adj[1], 0.3); const s0 = G.stats.searches; kd('KeyE'); const th = sim(10, () => G.stats.searches > s0 ? 'stop' : 0); ku('KeyE'); return { kind: c.kind, ok: G.stats.searches > s0, held: th }; };
window.holdE = (sec, until) => { kd('KeyE'); const t = sim(sec, () => until && until() ? 'stop' : 0); ku('KeyE'); return t; };
window.dlgButtons = () => [...document.querySelectorAll('#dlg button:not([disabled])')];
window.state = () => ({ day: G.day, time: G.hour + ':' + String(G.minute).padStart(2, '0'), p: [+G.p.x.toFixed(1), +G.p.y.toFixed(1)], hp: Math.round(G.p.hp), obj: objectiveInfo().text, unlocks: Object.keys(G.unlocks).join(','), blocking: UI.blocking(), mom: Moments.active, q: Game.Q.map(q => q.type).join(',') });
1;
