// Dead Embers: outdoor random encounters
(function () {
  const FG = (ids, opts) => { fight(ids, opts); return true; };
window.ENCOUNTERS = [
  {
    id: 'walker_pack', title: 'Shufflers in the Road', where: ['travel', 'street'], weight: 18,
    text: 'Four of the dead drift across the road ahead, heads lolling, dragging their feet through the grit. They have not noticed you yet. The wind is in your favor, for now.',
    choices: [
      { label: 'Fight them one at a time', success: () => FG(['walker', 'walker', 'walker'], { onWin: () => 'You go through their pockets. ' + give('cloth', 1) + '.' }) && 'They turn as one and lurch toward you.' },
      { label: 'Slip around through the yards', check: { attr: 'agi', diff: 4 },
        success: () => { xp(8); return 'You keep low and move through a gap in the fence. They drift past without a glance.'; },
        fail: () => { addNoise(1); return FG(['walker', 'walker'], {}) && 'A rotten board snaps under your boot. Two of them turn and shamble your way.'; } },
      { label: 'Throw a bottle to lure them off', success: () => { addNoise(1); xp(5); return 'The glass shatters far down the street. The dead follow the sound like iron to a magnet, and you walk on.'; } },
    ],
  },
  {
    id: 'lone_runner', title: 'Fast One', where: ['travel', 'street', 'depot'], weight: 12, minDay: 2,
    text: 'A scrape of bare feet on asphalt, then a shape sprinting out of an alley. This one is fresh, still fast, jaw hanging wide. You will not outrun it easily.',
    choices: [
      { label: 'Stand and fight', success: () => FG(['runner'], { onWin: () => 'It twitches once and goes still. ' + give('snack', 1) + ' from its coat.' }) && 'You plant your feet and raise your weapon.' },
      { label: 'Try to break away', check: { attr: 'agi', diff: 7 },
        success: () => { xp(12); return 'You vault a low wall and drop behind a dumpster. It overshoots and keeps running. You breathe again.'; },
        fail: () => { tire(15); return FG(['runner'], { noFlee: true }) && 'It is on you in seconds. There is nowhere left to run.'; } },
      { label: 'Climb onto the car roof', check: { attr: 'str', diff: 5 },
        success: () => { xp(10); tire(5); return 'You haul yourself up. It claws at the door until something else catches its attention and it leaves.'; },
        fail: () => { hurt(8, 'a fall from a car roof'); return FG(['runner'], {}) && 'Your grip slips and you land hard. It is already coming.'; } },
    ],
  },
  {
    id: 'bloater_corridor', title: 'The Swollen One', where: ['apartments', 'hospital', 'supermarket', 'factory'], weight: 10, minDay: 3,
    text: 'The stairwell is blocked by a bloated corpse, skin tight as a drum, wedged in the doorframe. It sloshes when it breathes. Whatever is inside it will not stay in if you cut it open.',
    choices: [
      { label: 'Fight it up close', success: () => FG(['bloater'], { onWin: () => { setStatus('sick', 6); return 'It bursts and a green cloud rolls over you. You stumble out coughing. ' + give('scrap', 1) + ' from the rubble.'; } }) && 'You grip your weapon and step into the smell.' },
      { label: 'Find another way around', check: { attr: 'per', diff: 4 },
        success: () => { xp(8); return 'You spot a maintenance hatch and crawl through. The bloater never hears you.'; },
        fail: () => { tire(10); return 'Every route ends in rubble or locked doors. You waste an hour and come back worn out.'; } },
      { label: 'Back away and leave it', success: () => 'You back down the stairs, one slow step at a time. Whatever was up there stays there.' },
    ],
  },
  {
    id: 'screamer_cry', title: 'The Screaming Girl', where: ['travel', 'street', 'apartments', 'police'], weight: 10, minDay: 3,
    text: 'A thin figure in a torn dress stands in the middle of the road, mouth stretched impossibly wide. The first note of the scream is already building. Every dead thing within a mile will hear this.',
    choices: [
      { label: 'Silence it fast', check: { attr: 'agi', diff: 6 },
        success: () => { xp(15); return 'You close the distance before the scream peaks and drive your blade home. It chokes off into a wet whisper. Silence returns.'; },
        fail: () => { addNoise(3); return FG(['screamer', 'walker', 'walker', 'walker'], {}) && 'The scream tears through the street. Doors bang open. The dead pour out.'; } },
      { label: 'Shoot it from range', req: () => has('pistol') && has('ammo'), reqText: 'Needs a pistol and ammo',
        check: { attr: 'per', diff: 5 },
        success: () => { take('ammo', 1); xp(12); addNoise(1); return 'One shot, clean through the throat. The shot is loud, but it is nothing next to the scream.'; },
        fail: () => { take('ammo', 1); addNoise(3); return FG(['screamer', 'walker', 'walker'], {}) && 'The shot goes wide. The scream does not.'; } },
      { label: 'Run before it starts', check: { attr: 'end', diff: 5 },
        success: () => { tire(10); return 'You bolt around the corner as the first cry rips out. You keep running until the sound is a thin echo.'; },
        fail: () => { addNoise(2); return FG(['screamer', 'walker', 'walker'], {}) && 'You do not make it far. The dead answer the call.'; } },
    ],
  },
  {
    id: 'brute_block', title: 'The Wall of Meat', where: ['travel', 'street', 'depot', 'factory'], weight: 8, minDay: 4,
    text: 'A hulking corpse in the remains of a hi-vis vest stands where the road narrows between two wrecks. Its arms are knotted with muscle and it has not seen you yet. You cannot go through without waking it.',
    choices: [
      { label: 'Take it head on', success: () => FG(['brute'], { onWin: () => 'It finally topples. ' + give('scrap', 2) + ', ' + give('parts', 1) + ' from its toolbelt.' }) && 'It turns, and the ground shakes under its first step.' },
      { label: 'Squeeze past the wrecks', check: { attr: 'agi', diff: 6 },
        success: () => { xp(14); return 'You slide through the gap between a van and a bus, holding your breath. It sniffs at the air and stays put.'; },
        fail: () => { addNoise(2); return FG(['brute'], {}) && 'Your pack catches a bumper with a loud clang. It roars.'; } },
      { label: 'Go around the long way', success: () => { tire(12); passTime(2); return 'It costs you two hours and a lot of breath, but nothing hunts you on the long road.'; } },
    ],
  },
  {
    id: 'zdog_pack', title: 'Hounds', where: ['travel', 'street', 'farm', 'forest'], weight: 11, minDay: 2,
    text: 'Low growls from the hedge. Three dogs, ribs showing through grey fur, eyes clouded and rimmed with red. They circle without barking, which is worse than if they barked.',
    choices: [
      { label: 'Fight them off', success: () => FG(['zdog', 'zdog', 'zdog'], { onWin: () => 'The last one stops twitching. ' + give('rawmeat', 1) + ' is scavenged, though you hesitate to eat it.' }) && 'The first one lunges, and the rest follow.' },
      { label: 'Back slowly toward a wall', check: { attr: 'per', diff: 5 },
        success: () => { xp(10); return 'You read the alpha and hold your ground until it loses interest. The pack trots away.'; },
        fail: () => { return FG(['zdog', 'zdog'], {}) && 'The alpha lunges the moment you flinch.'; } },
      { label: 'Toss them some food', req: () => has('canned') || has('rawmeat'), reqText: 'Needs food to throw',
        success: () => { if (!take('rawmeat', 1)) take('canned', 1); return 'You hurl it far to one side. They tear into it and you walk the other way, quickly.'; } },
    ],
  },
  {
    id: 'surrounded_survivor', title: 'Cornered', where: ['travel', 'street', 'supermarket', 'gas'], weight: 9,
    text: 'A man is backed against a parked truck, swinging a tire iron at six of the dead closing in around him. He sees you and yells for help through cracked lips. He will not last another minute alone.',
    choices: [
      { label: 'Join the fight', success: () => FG(['walker', 'walker', 'walker', 'walker'], { onWin: () => {
          const s = recruit({ name: pick(['Daniel', 'Marcus', 'Teo', 'Hollis']), trait: 'grateful', skills: { combat: 3, scav: 2 } });
          xp(20);
          return s ? 'He drops the tire iron and gasps out his thanks. He asks to follow you home, and you let him.' : 'He thanks you and limps away. The shelter has no room.';
        } }) && 'You charge in beside him and the dead turn on both of you.' },
      { label: 'Make noise to draw them off', check: { attr: 'cha', diff: 5 },
        success: () => { addNoise(2); xp(15); const s = recruit({ trait: 'grateful' }); return s ? 'You shout and bang a pipe on a lamp post. Half of them peel away and he escapes. He follows you after that.' : 'The dead peel away and he escapes, but you cannot take him in.'; },
        fail: () => { addNoise(3); hurt(6, 'a zombie bite'); return 'The dead ignore you and finish what they started. You flee with a bleeding arm and his screaming in your ears.'; } },
      { label: 'Walk away', success: () => { addMorale(-8); return 'You turn and keep walking. His cries stop after a while. You carry that for the rest of the day.'; } },
    ],
  },
  {
    id: 'bitten_stranger', title: 'A Mercy Asked', where: ['travel', 'street', 'apartments', 'hospital'], weight: 8,
    text: 'A woman sits in a doorway with a bandage soaked black around her forearm. She is not crying. She tells you she was bitten this morning, and asks you to either help her or finish it quickly.',
    choices: [
      { label: 'Give her antibiotics', req: () => has('antibiotics'), reqText: 'Needs antibiotics',
        success: () => { take('antibiotics', 1); xp(15); addMorale(5); return chance(0.25) ? 'She takes the pills and the fever breaks within the day. Against all odds she recovers. ' + give('canned', 2) + ' is pressed into your hands as thanks.' : 'She swallows the pills and thanks you. By nightfall you know it did not work, but she was not afraid at the end.'; } },
      { label: 'Grant her mercy', success: () => { addMorale(-6); xp(8); return 'You do it fast. She whispers thanks. In her pack you find ' + give('bandage', 1) + ' and ' + give('cigs', 2) + '.'; } },
      { label: 'Leave her be', success: () => { addMorale(-3); return 'You leave her in the doorway with her water bottle. Behind you, she begins to hum.'; } },
    ],
  },
  {
    id: 'wounded_stranger', title: 'Wounded Man', where: ['travel', 'street', 'forest', 'farm'], weight: 9,
    text: 'A man lies against a fence post with a deep gash in his thigh and a pistol he cannot raise. He says he can walk if someone wraps it. He does not look like a raider, but nobody does at first.',
    choices: [
      { label: 'Bandage him up', req: () => has('bandage'), reqText: 'Needs a bandage',
        success: () => { take('bandage', 1); xp(12); const s = recruit({ trait: 'loyal', skills: { combat: 2, scav: 2 } }); return s ? 'You dress the wound. He grips your hand, says he has nowhere to go, and asks to come along.' : 'You dress the wound. He thanks you and limps off alone.'; } },
      { label: 'Search him first', check: { attr: 'per', diff: 4 },
        success: () => 'You find nothing hostile on him. You take ' + give('ammo', 3) + ' and leave him a little water. He does not argue.',
        fail: () => { hurt(6, 'a hidden knife'); return 'You are checking his pockets when his knife bites your side. He crawls away into the weeds, and you let him go.'; } },
      { label: 'Walk on', success: () => 'You nod and keep moving. In this city, hard calls are the only calls.' },
    ],
  },
  {
    id: 'lost_kids', title: 'Two Small Faces', where: ['travel', 'street', 'apartments', 'supermarket'], weight: 6, minDay: 2,
    text: 'You hear whispering behind a bus shelter. Two kids, maybe nine and twelve, huddle together with an empty backpack. They have not eaten in two days and they do not trust you.',
    choices: [
      { label: 'Share your food', req: () => has('canned') || has('snack'), reqText: 'Needs food',
        success: () => { if (!take('snack', 1)) take('canned', 1); xp(15); addMorale(8); const s = recruit({ name: 'Mina', trait: 'scared', skills: { scav: 1 } }); return s ? 'They eat in silence. The older one asks if they can come with you, and you cannot say no.' : 'They eat and thank you. You point them toward a safer block.'; } },
      { label: 'Persuade them to follow', check: { attr: 'cha', diff: 5 },
        success: () => { xp(10); const s = recruit({ name: 'Jonah', trait: 'quiet', skills: { scav: 1 } }); return s ? 'You crouch, speak softly, and offer your hand. After a long moment the older one takes it.' : 'They trust you enough to talk, but you cannot house them.'; },
        fail: () => 'They bolt through a gap in the fence before you finish the sentence. You do not chase them.' },
      { label: 'Leave them', success: () => { addMorale(-10); return 'You walk away. Their faces follow you all the way home.'; } },
    ],
  },
  {
    id: 'hospital_doctor', title: 'The Hidden Doctor', where: ['hospital'], weight: 10, once: true, minDay: 2,
    text: 'Behind a barricaded supply door you hear a click, a shotgun being cocked. A tired voice asks what you want. A woman in a stained white coat peers through the crack and says she has been alone for months.',
    choices: [
      { label: 'Offer her a place at the shelter', check: { attr: 'cha', diff: 5 },
        success: () => { xp(25); const s = recruit({ name: 'Dr. Imara Voss', trait: 'steady', skills: { med: 5, scav: 1 } }); return s ? 'She looks at you for a long time. Then she picks up a worn medical bag and says she is coming. Your shelter just got a doctor.' : 'She wants to come, but the shelter cannot hold anyone more. She gives you a few supplies instead. ' + give('bandage', 2) + '.'; },
        fail: () => 'She shakes her head and the door closes. "I have seen what people do." You hear the bolts slide.' },
      { label: 'Trade her supplies for medicine', req: () => has('canned', 2), reqText: 'Needs 2 Canned Food',
        success: () => { take('canned', 2); xp(8); return 'She passes through a bundle. ' + give('medkit', 1) + ', ' + give('antibiotics', 1) + '. She does not smile, but she takes the cans.'; } },
      { label: 'Apologize and leave', success: () => 'You lower your weapon and back out of the ward. Her door stays shut.' },
    ],
  },
  {
    id: 'raider_ambush', title: 'Ambush', where: ['travel', 'street', 'depot', 'factory', 'tollcamp'], weight: 12, minDay: 2,
    text: 'A trip wire, a clatter of cans, and three men step out from behind a wrecked van. They wear stolen riot gear and grin like they already won. "Everything you got," the tallest says.',
    choices: [
      { label: 'Fight', success: () => FG(['raider', 'raider', 'raider'], { onWin: () => 'You drag yourself upright. Their packs hold ' + give('ammo', 3) + ', ' + give('canned', 1) + ' and ' + give('cigs', 3) + '.' }) && 'You grip your weapon and meet the first one head on.' },
      { label: 'Talk your way out', check: { attr: 'cha', diff: 6 },
        success: () => { xp(15); return 'You mention the Warden by name and feign a deal in progress. They look at each other and step aside.'; },
        fail: () => { const c = has('cigs', 2) ? (take('cigs', 2), '2 Cigarettes') : 'your pocket change'; hurt(8, 'a beating'); return 'They are not interested in talking. They take ' + c + ' and leave you bruised in the dirt.'; } },
      { label: 'Run for it', check: { attr: 'agi', diff: 6 },
        success: () => { tire(10); return 'You cut through a side street and keep running. Their shouts fade behind you.'; },
        fail: () => { hurt(10, 'raider gunfire'); return 'A shot cracks past your ear, then something hits your leg. You limp away alive, mostly.'; } },
    ],
  },
  {
    id: 'toll_collector', title: 'The Toll', where: ['travel', 'street', 'tollcamp'], weight: 12,
    text: 'A rope across the road, a hand-painted sign reading TOLL. Two Tollmen lean on a barrel fire. "Warden says everyone pays to walk his roads," one says, tapping a bat against his palm.',
    choices: [
      { label: 'Pay the toll', success: () => { if (take('cigs', 3)) return 'You hand over three cigarettes. They wave you through with mock courtesy.'; if (take('canned', 1)) return 'No cigarettes, so you hand over a can of food. They wave you through, sneering.'; hurt(5, 'a tollman beating'); return 'You have nothing worth taking, so they take a bit of flesh instead.'; } },
      { label: 'Fight them', success: () => FG(['tollman', 'tollman'], { onWin: () => 'Their toll box is lighter than expected. ' + give('cigs', 4) + ' and ' + give('ammo', 2) + '.' }) && 'You step toward the rope. The bat comes up.' },
      { label: 'Talk down the price', check: { attr: 'cha', diff: 5 },
        success: () => { xp(12); return 'You lean on the Warden\'s reputation and a tired smile. They wave you through for free.'; },
        fail: () => { take('cigs', 3); return 'They laugh in your face. The price just went up, and they take whatever cigarettes you have.'; } },
    ],
  },
  {
    id: 'wandering_trader', title: 'Peddler on the Road', where: ['travel', 'street', 'farm'], weight: 9, night: false,
    text: 'A man with a hand cart and a shotgun across his knees raises one palm. "Trade? No tricks." His cart rattles with tins, tools, and things you cannot name.',
    choices: [
      { label: 'Browse his goods', success: () => { openTrader(); return 'He tips his hat and lays out his wares on a tarp.'; } },
      { label: 'Ask about the roads', check: { attr: 'cha', diff: 4 },
        success: () => { xp(8); return 'He tells you which blocks are crawling and which are clear. ' + give('cigs', 1) + ' for your trouble.'; },
        fail: () => 'He shrugs. "Everyone has a story. Mine is not for sale."' },
      { label: 'Wave him on', success: () => 'You nod. He nods back, and the cart rattles off.' },
    ],
  },
  {
    id: 'radio_hermit', title: 'The Hermit with the Dials', where: ['radiotower', 'electronics', 'travel'], weight: 8, once: true,
    cond: () => !flag('got_coil'),
    text: 'A thin man with a headset sits in a trailer surrounded by dials and wires. He says he has been listening to Haven\'s broadcast for months. "It never changes," he says. "Not a single word. Does that sound like a person to you?"',
    choices: [
      { label: 'Ask him about the broadcast', check: { attr: 'int', diff: 5 },
        success: () => { journal('The Hermit\'s Theory', 'The hermit says Haven\'s broadcast loops every 41 minutes with identical pauses. He thinks it is a recording left by someone who is no longer there. He was kind enough to give me a radio coil to tune my own set.'); setFlag('got_coil', true); xp(20); return 'You trade theories for an hour. He goes quiet, then hands you a small wire-wound part. ' + give('radio_coil', 1) + '.'; },
        fail: () => { journal('The Hermit\'s Theory', 'The hermit talks about Haven\'s signal without end. I follow little of it, but he insists the broadcast is not what it seems.'); return 'He talks until your head hurts. You understand one thing: the broadcast loops, and he does not trust it.'; } },
      { label: 'Trade a snack for batteries', req: () => has('snack') || has('canned'), reqText: 'Needs food',
        success: () => { if (!take('snack', 1)) take('canned', 1); return 'He swaps a little dusty pair with you. ' + give('batteries', 2) + '.'; } },
      { label: 'Move on', success: () => 'You leave him to his dials. The static follows you down the road.' },
    ],
  },
  {
    id: 'hidden_stash', title: 'Loose Brick', where: ['any'], weight: 12,
    text: 'Something catches your eye in an alley wall: a brick slightly out of line, with scratch marks around it. Someone hid something here, and never came back for it.',
    choices: [
      { label: 'Pry it open', check: { attr: 'per', diff: 4 },
        success: () => { xp(10); return 'Behind the brick, a coffee tin. Inside: ' + give('canned', 1) + ', ' + give('ammo', 3) + ', ' + give('cigs', 2) + '.'; },
        fail: () => 'You find only dust and an old bus ticket. Someone cleaned this out long ago.' },
      { label: 'Smash the wall', success: () => { addNoise(2); return 'You hammer the bricks free. ' + give('cloth', 1) + ' and ' + give('scrap', 1) + ' tumble out, and the noise carries.'; } },
      { label: 'Leave it', success: () => 'It might be a trap. It might be nothing. You walk on.' },
    ],
  },
  {
    id: 'collapsing_floor', title: 'Rotten Boards', where: ['apartments', 'factory', 'supermarket', 'depot'], weight: 9,
    text: 'The upper walkway is stacked with intact crates, a fortune in dry goods. The floor under them sags, the boards dark and soft with rot. One wrong step and you will find out how deep the basement goes.',
    choices: [
      { label: 'Cross carefully', check: { attr: 'agi', diff: 5 },
        success: () => { xp(10); return 'You hug the wall and place each step like a thief. The crates hold ' + give('canned', 2) + ', ' + give('parts', 1) + ' and ' + give('wood', 2) + '.'; },
        fail: () => { hurt(10, 'a floor collapse'); addNoise(2); return 'The boards give way. You fall through into the basement with a sickening crack. You claw out with nothing to show for it.'; } },
      { label: 'Drag a crate with a hook', req: () => has('pipe') || has('bat') || has('axe'), reqText: 'Needs a pipe, bat or axe',
        success: () => { xp(6); return 'You hook one crate and haul it toward you. ' + give('canned', 1) + ' is all that you get, but it is safe.'; } },
      { label: 'Skip it', success: () => 'You leave the crates. The floor groans behind you, as if relieved.' },
    ],
  },
  {
    id: 'locked_safe', title: 'The Safe', where: ['police', 'apartments', 'supermarket', 'electronics', 'gas'], weight: 8,
    text: 'A squat steel safe sits in the back office, door sealed, with a cracked keypad. Whoever locked it believed it mattered. Maybe they were right.',
    choices: [
      { label: 'Crack the keypad', check: { attr: 'int', diff: 6 },
        success: () => { xp(20); return 'You trace the wear patterns on the keys and try three combinations. The third clicks. Inside: ' + give('ammo', 5) + ', ' + give('cigs', 4) + ', ' + give('batteries', 2) + '.'; },
        fail: () => 'The keypad locks and beeps angrily. You give up and walk away.' },
      { label: 'Break it open', check: { attr: 'str', diff: 6 },
        success: () => { addNoise(3); xp(15); return 'You wedge a bar in the seam and heave. The door groans, then pops. ' + give('ammo', 4) + ', ' + give('cigs', 3) + '. Everyone nearby heard that.'; },
        fail: () => { addNoise(3); hurt(4, 'a slipped crowbar'); return 'The bar slips and splits your knuckles. The noise rang out for blocks, and the safe did not budge.'; } },
      { label: 'Leave it', success: () => 'Some things are not worth the trouble. You close the office door behind you.' },
    ],
  },
  {
    id: 'abandoned_car', title: 'Abandoned Sedan', where: ['travel', 'street', 'gas', 'depot'], weight: 14,
    text: 'A sedan sits half on the curb, driver door open, windshield spiderwebbed. The seats are stained brown. The trunk is shut and the hood is ajar.',
    choices: [
      { label: 'Check the trunk', success: () => { xp(5); return chance(0.5) ? 'The trunk holds a spare tire, a jack, and ' + give('parts', 1) + ' and ' + give('cloth', 1) + '.' : 'The trunk holds a dead suitcase and little else. ' + give('cloth', 1) + '.'; } },
      { label: 'Siphon the tank', req: () => has('pipe') || has('knife'), reqText: 'Needs a pipe or knife',
        check: { attr: 'int', diff: 4 },
        success: () => { xp(8); return 'You puncture the tank and fill a can. ' + give('fuel', 2) + '.'; },
        fail: () => { setStatus('sick', 3); return 'You get a mouthful of fuel and cough for an hour. The tank was empty anyway.'; } },
      { label: 'Strip the engine', check: { attr: 'str', diff: 5 },
        success: () => { addNoise(1); xp(8); return 'You wrestle the hood open and tear free what you can. ' + give('engine_parts', 1) + ' and ' + give('parts', 2) + '.'; },
        fail: () => { hurt(5, 'a scraped knuckle'); return 'A bolt will not turn. You bloody your hand and give up.'; } },
    ],
  },
  {
    id: 'acid_rain', title: 'Ash Rain', where: ['travel', 'street', 'farm', 'forest', 'river'], weight: 9,
    text: 'The sky goes the color of old bruises and ash begins to fall, then something worse: a thin rain that stings your skin. Somewhere a fire has fed the clouds. You need cover, or a lot of luck.',
    choices: [
      { label: 'Push through it', check: { attr: 'end', diff: 5 },
        success: () => { tire(15); xp(8); return 'You pull your collar up and walk through. The rain burns, but you reach clear air.'; },
        fail: () => { hurt(10, 'acid rain'); setStatus('sick', 4); return 'The rain eats at your skin and eyes. You find shelter, blistered and shaking.'; } },
      { label: 'Wait it out under cover', success: () => { passTime(3); return 'You wedge yourself under a bus shelter and wait three hours while the street hisses around you. Something dripped on your cloth.'; } },
      { label: 'Collect the runoff', req: () => has('cloth'), reqText: 'Needs cloth',
        success: () => { take('cloth', 1); setStatus('sick', 2); return 'You filter the runoff through a cloth, but a few drops go in. ' + give('chem', 1) + ' for your trouble.'; } },
    ],
  },
  {
    id: 'supply_drop', title: 'Fallen Crate', where: ['military'], weight: 10, minDay: 3,
    text: 'A crate on a dead parachute lies in the middle of the yard. Stenciled letters read PROPERTY OF AVC GARRISON. The seal is intact. Nobody has come for it in months.',
    choices: [
      { label: 'Open it carefully', check: { attr: 'int', diff: 5 },
        success: () => { xp(20); return 'You spot a trip wire inside the lid and cut it. Inside: ' + give('ammo', 6) + ', ' + give('medkit', 1) + ', ' + give('canned', 3) + '.'; },
        fail: () => { hurt(8, 'a booby trap'); addNoise(2); return 'A flash of light and a bang. You stagger back, ears ringing. You grab ' + give('canned', 1) + ' from the wreckage.'; } },
      { label: 'Smash the lid with a bar', req: () => has('pipe') || has('axe') || has('bat'), reqText: 'Needs a pipe, axe or bat',
        success: () => { addNoise(3); xp(10); return 'You hammer at the seal until it splits. ' + give('ammo', 4) + ', ' + give('canned', 2) + '. The noise brings answers.'; } },
      { label: 'Leave it', success: () => 'You do not trust a gift that comes down from the sky. You walk away.' },
    ],
  },
  {
    id: 'gas_siphon', title: 'The Last Pump', where: ['gas'], weight: 12,
    text: 'The underground tanks of this station might still hold something. A manual pump is chained to the wall, rusted but whole. A figure shuffles on the far side of the forecourt, not yet aware of you.',
    choices: [
      { label: 'Work the pump', check: { attr: 'str', diff: 4 },
        success: () => { addNoise(1); xp(8); return 'The pump screams with every stroke, but fuel gurgles up. ' + give('fuel', 3) + '.'; },
        fail: () => { tire(15); return 'The handle fights you. You get only a few drops before your arms give out.'; } },
      { label: 'Siphon from the wrecks', success: () => { xp(5); return 'You work through the wrecks one by one, quiet as a thief. ' + give('fuel', 1) + ' for an hour of work.'; } },
      { label: 'Deal with the walker first', success: () => FG(['walker'], { onWin: () => 'With the forecourt quiet, you fill a can undisturbed. ' + give('fuel', 2) + '.' }) && 'You step out and meet it.' },
    ],
  },
  {
    id: 'river_fishing', title: 'Slow Water', where: ['river'], weight: 12, night: false,
    text: 'The river runs brown but slow, the current barely disturbing the reeds. Silver shapes flicker in the shallows. Nobody has fished here in a year, and the fish have not forgotten how to be fat.',
    choices: [
      { label: 'Fish with a line', check: { attr: 'per', diff: 4 },
        success: () => { xp(8); return 'You wait, and wait, then the line jerks. You land three plump fish. ' + give('meal', 1) + ' once cooked, and ' + give('rawmeat', 1) + '.'; },
        fail: () => 'Three hours and not a single bite. The fish, wisely, ignore you.' },
      { label: 'Wade in and grab', check: { attr: 'agi', diff: 6 },
        success: () => { xp(12); return 'You snatch a fish from the shallows with your bare hands. ' + give('rawmeat', 2) + '.'; },
        fail: () => { setStatus('sick', 3); return 'You slip and swallow a mouthful of river. You crawl out gagging.'; } },
      { label: 'Fill bottles with water', success: () => 'You boil it later and drink. ' + give('dirtywater', 2) + '.' },
    ],
  },
  {
    id: 'forest_snare', title: 'Tracks in the Mud', where: ['forest', 'farm'], weight: 12, night: false,
    text: 'Fresh tracks lace the mud: deer, maybe, or something smaller. A natural funnel between two fallen trunks would make a perfect place for a snare. Or you could follow the tracks.',
    choices: [
      { label: 'Set a snare', req: () => has('cloth') || has('scrap'), reqText: 'Needs cloth or scrap',
        success: () => { if (!take('cloth', 1)) take('scrap', 1); passTime(2); xp(6); return chance(0.7) ? 'Two hours later, the line has pulled tight. ' + give('rawmeat', 2) + '.' : 'You wait two hours. The snare stays empty.'; } },
      { label: 'Stalk the tracks', check: { attr: 'per', diff: 5 },
        success: () => { xp(12); return 'You follow the prints to a deer, still as a stone. A single bolt or blow, and ' + give('rawmeat', 3) + '.'; },
        fail: () => { tire(10); return 'The trail doubles back on itself. You lose an hour and the light.'; } },
      { label: 'Forage for roots', success: () => 'You scrape the ground for edible roots. ' + give('veg', 1) + '.' },
    ],
  },
  {
    id: 'pharmacy_shelf', title: 'Back of the Pharmacy', where: ['apartments'], weight: 8,
    text: 'The ground-floor pharmacy has been picked clean, or so it looks. Behind the counter, a roll shutter hides the stockroom. Beneath it, a thin slice of dark light.',
    choices: [
      { label: 'Lift the shutter quietly', check: { attr: 'agi', diff: 4 },
        success: () => { xp(10); return 'Slow, inch by inch. Inside, untouched shelves. ' + give('painkillers', 2) + ', ' + give('bandage', 2) + ', ' + give('antibiotics', 1) + '.'; },
        fail: () => { addNoise(2); return 'The shutter shrieks upward. The shelves are bare, and something heard you.'; } },
      { label: 'Kick it in', check: { attr: 'str', diff: 4 },
        success: () => { addNoise(2); xp(8); return 'It crumples. You grab ' + give('painkillers', 1) + ' and ' + give('bandage', 1) + ' before the dust settles.'; },
        fail: () => { hurt(4, 'a bruised foot'); addNoise(2); return 'The shutter holds and your foot does not. You limp out with nothing.'; } },
      { label: 'Check the counter drawers', success: () => 'Most are empty. Under a sheaf of invoices you find ' + give('bandage', 1) + '.' },
    ],
  },
  {
    id: 'corpse_pile', title: 'The Pile', where: ['travel', 'street', 'hospital', 'depot'], weight: 9,
    text: 'A heap of bodies lies behind a chain-link fence, stacked by someone who gave up. Flies hum in the heat. Something in the pile twitches, or perhaps it was only the wind.',
    choices: [
      { label: 'Search the bodies', check: { attr: 'end', diff: 4 },
        success: () => { xp(8); return 'You hold your breath and dig through pockets. ' + give('cigs', 2) + ', ' + give('cloth', 1) + ', ' + give('bandage', 1) + '.'; },
        fail: () => { setStatus('sick', 4); addNoise(1); return 'The stench is too much. You retch and stumble back, sick and empty-handed.'; } },
      { label: 'Poke it with a stick first', req: () => has('pipe') || has('bat') || has('axe') || has('machete'), reqText: 'Needs a weapon',
        success: () => FG(['walker', 'walker'], { onWin: () => 'Now the pile stays still. ' + give('cigs', 2) + ' and ' + give('cloth', 1) + '.' }) && 'A hand shoots out and grips the pipe. Two of them rise from the heap.' },
      { label: 'Leave them', success: () => 'You cross to the other side of the road and do not look back.' },
    ],
  },
  {
    id: 'church_bell', title: 'The Bell', where: ['travel', 'street', 'apartments'], weight: 7, minDay: 2,
    text: 'A small church stands at the end of the block, its bell rope hanging down through the broken roof. In the nave, a stack of canned food waits on the altar. The rope is tied off, too neatly. Someone set a trap here.',
    choices: [
      { label: 'Cut the rope first', check: { attr: 'per', diff: 5 },
        success: () => { xp(15); return 'You trace the line to the bell and cut it. Silence. The altar yields ' + give('canned', 3) + ' and ' + give('cigs', 2) + '.'; },
        fail: () => { addNoise(3); return FG(['walker', 'walker', 'walker'], {}) && 'The bell clangs once, then again. Every dead thing within a mile starts to turn.'; } },
      { label: 'Grab the food and run', check: { attr: 'agi', diff: 5 },
        success: () => { xp(8); return 'You snatch ' + give('canned', 2) + ' and are out before the rope tightens.'; },
        fail: () => { addNoise(3); return FG(['walker', 'walker'], {}) && 'The bell rings out above you, long and loud.'; } },
      { label: 'Say a prayer and walk on', success: () => { addMorale(2); return 'You do not trust a church with a trap. You leave it in peace.'; } },
    ],
  },
  {
    id: 'mirror_message', title: 'Writing on the Mirror', where: ['apartments', 'hospital', 'police', 'electronics'], weight: 6, once: true,
    text: 'In a dusty bathroom, someone has smeared words across the mirror in what might be lipstick: HAVEN IS A LIE? A coffee mug on the sink still has a ring of dried tea. Whoever wrote it left in a hurry.',
    choices: [
      { label: 'Search the room for clues', check: { attr: 'int', diff: 5 },
        success: () => { journal('A Message in Lipstick', 'In an empty bathroom someone wrote HAVEN IS A LIE? on the mirror. In the cabinet I found a torn note: "No convoys came back from the north pass." I do not know what to believe.'); xp(18); return 'Behind the cabinet you find a torn note in the same hand, and ' + give('canned', 1) + '. The note is not good news.'; },
        fail: () => { journal('A Message in Lipstick', 'In an empty bathroom someone wrote HAVEN IS A LIE? on the mirror. I found nothing else.'); return 'You tear the room apart and find only the mirror, and the question.'; } },
      { label: 'Wipe it away', success: () => { addMorale(1); return 'You wipe the mirror with your sleeve. Some doubts are better not fed.'; } },
      { label: 'Add your own reply', success: () => { xp(5); journal('A Message in Lipstick', 'I saw a message on a mirror asking if Haven is a lie. I wrote YES under it, just in case someone else comes looking.'); return 'You scrawl YES beneath it. Someone else may find that comforting, or terrifying.'; } },
    ],
  },
  {
    id: 'horde_edge', title: 'The Edge of a Horde', where: ['travel', 'street'], weight: 6, minDay: 6, night: true,
    text: 'The ground carries a low murmur, a sound like surf. Down the street, a slow river of the dead moves in the dark, forty at least, drawn by something you cannot see. You are upwind. You are not safe.',
    choices: [
      { label: 'Hide and wait for them to pass', check: { attr: 'end', diff: 6 },
        success: () => { xp(20); passTime(2); return 'You crouch in a ditch with your hand over your mouth while the dead file past. It takes two hours. They never look down.'; },
        fail: () => { addNoise(3); return FG(['walker', 'walker', 'walker', 'runner'], {}) && 'A straggler spots you. It makes a sound, and the others turn.'; } },
      { label: 'Slip away down a side street', check: { attr: 'agi', diff: 6 },
        success: () => { xp(14); return 'You edge away from the column and break into a run once there are walls between you.'; },
        fail: () => { addNoise(2); return FG(['walker', 'walker', 'runner'], {}) && 'Something grabs your coat. You fight free, but not before others notice.'; } },
      { label: 'Make a diversion with a bang', req: () => has('batteries') || has('chem'), reqText: 'Needs batteries or chemicals',
        success: () => { if (!take('chem', 1)) take('batteries', 1); addNoise(3); xp(18); return 'You toss a small charge toward a far building. The dead follow the flash, and you slip away.'; } },
    ],
  },
  {
    id: 'night_stalkers', title: 'Eyes in the Dark', where: ['travel', 'street', 'farm', 'forest'], weight: 9, night: true,
    text: 'Night makes every shape worse. Two shadows drift near the edge of your light, too still to be alive and too deliberate to be dead. One of them turns its head.',
    choices: [
      { label: 'Douse your light and hold still', check: { attr: 'per', diff: 5 },
        success: () => { xp(10); return 'You go dark and listen. They lose you and drift off. When your eyes adjust, the road is empty.'; },
        fail: () => FG(['walker', 'walker', 'runner'], {}) && 'A snap of twigs. They were closer than you thought.' },
      { label: 'Charge them', success: () => FG(['walker', 'walker'], { onWin: () => 'Both lie still in the dirt. ' + give('cloth', 1) + '.' }) && 'You raise your weapon and meet them before they can circle.' },
      { label: 'Retreat the way you came', success: () => { tire(8); passTime(1); return 'You backtrack for an hour in the dark, hands out in front of you. Whatever they were, they did not follow.'; } },
    ],
  },
  {
    id: 'farm_scarecrows', title: 'Field of Scarecrows', where: ['farm'], weight: 7,
    text: 'Rows of scarecrows stand in the rotted field. One of them is wearing a recent jacket, and has a hand missing. Behind them, a barn door swings on one hinge. Something inside smells like food.',
    choices: [
      { label: 'Search the barn', check: { attr: 'per', diff: 4 },
        success: () => { xp(10); return 'In a sealed bin you find a farmer\'s reserve. ' + give('veg', 2) + ', ' + give('canned', 1) + ', ' + give('wood', 2) + '.'; },
        fail: () => FG(['walker', 'walker'], {}) && 'The barn was a nest. Two of the dead shamble out of the dark.' },
      { label: 'Check the jacket', success: () => { xp(4); return 'In the pocket: ' + give('cigs', 1) + ' and a note about a well that went bad. You keep the first and file the second away.'; } },
      { label: 'Keep your distance', success: () => 'You stay out of the rows. Some things in a field are not what they seem.' },
    ],
  },
];
})();
